# Generated by Django 2.2.2 on 2019-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
