# Generated by Django 2.2.2 on 2019-07-08 13:29

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190608_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('short_description', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('date', models.DateField()),
                ('image', image_cropping.fields.ImageRatioField('image', '340x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
