# Generated by Django 2.2.2 on 2019-07-08 13:37

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190708_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '340x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
