# Generated by Django 2.2.2 on 2019-07-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190708_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cropping',
        ),
    ]
