# Generated by Django 2.2.2 on 2019-07-19 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
