# Generated by Django 2.2.2 on 2019-07-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0006_topic_date'),
        ('news', '0009_remove_article_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='album',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='photogallery.Topic'),
        ),
    ]
