# Generated by Django 2.2.2 on 2019-07-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photogallery.Topic'),
        ),
    ]
