# Generated by Django 2.2.2 on 2019-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medalist',
            name='medalist_type',
            field=models.CharField(choices=[('gl', 'Золотий медаліст'), ('sl', 'Срібний медаліст')], default='gl', max_length=2),
        ),
    ]
