# Generated by Django 2.2.2 on 2019-07-31 10:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('achievements', '0002_medalist_medalist_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='AllMedalist',
        ),
    ]
