# Generated by Django 2.2.2 on 2019-07-31 11:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('achievements', '0003_auto_20190731_1358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllMedalist',
            new_name='Year',
        ),
    ]
