# Generated by Django 2.2.2 on 2019-07-31 11:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('achievements', '0004_auto_20190731_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medalist',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
