# Generated by Django 2.2.2 on 2019-07-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    atomic = False
    dependencies = [
        ('achievements', '0005_auto_20190731_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMedalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('medalist_type', models.CharField(choices=[('gl', 'Золотий медаліст'), ('sl', 'Срібний медаліст')], default='gl', max_length=2)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.AllMedalist')),
            ],
        ),
    ]
