# Generated by Django 2.2.2 on 2019-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_allmedalist_medalist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allmedalist',
            options={'verbose_name': 'Медалісти', 'verbose_name_plural': 'Медалісти'},
        ),
        migrations.AlterModelOptions(
            name='medalist',
            options={'verbose_name': 'Медаліст', 'verbose_name_plural': 'Медалісти'},
        ),
        migrations.AlterField(
            model_name='allmedalist',
            name='year',
            field=models.IntegerField(verbose_name='Рік'),
        ),
        migrations.AlterField(
            model_name='medalist',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='medalist',
            name='medalist_type',
            field=models.CharField(choices=[('gl', 'Золотий медаліст'), ('sl', 'Срібний медаліст')], default='gl', max_length=2, verbose_name='Тип медаліста'),
        ),
        migrations.AlterField(
            model_name='medalist',
            name='second_name',
            field=models.CharField(max_length=20, verbose_name='Прізвище'),
        ),
    ]
