# Generated by Django 2.2.2 on 2020-03-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_auto_20190831_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Рік')),
                ('subject', models.CharField(max_length=20, verbose_name='Предмет')),
                ('stage', models.CharField(choices=[('s1', 'II (районний) етап'), ('s2', 'III (обласний) етап'), ('s3', 'II (обласний) етап МАН')], default='s1', max_length=2, verbose_name='Етап')),
            ],
            options={
                'verbose_name': 'Олімпіадний рік',
                'verbose_name_plural': 'Олімпіадні роки',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('place', models.CharField(choices=[('gl', '1 місце'), ('sl', '2 місце'), ('bz', '3 місце')], default='gl', max_length=2, verbose_name='Місце')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Subject')),
            ],
            options={
                'verbose_name': 'Переможець',
                'verbose_name_plural': 'Переможці',
            },
        ),
    ]
