# Generated by Django 2.2.2 on 2020-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_auto_20200301_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='class_n',
            field=models.CharField(default=7, max_length=20, verbose_name='Клас'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winner',
            name='teacher',
            field=models.CharField(default=5, max_length=20, verbose_name='Вчитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winner',
            name='place',
            field=models.CharField(choices=[('gl', 'I'), ('sl', 'II'), ('bz', 'III')], default='gl', max_length=2, verbose_name='Місце'),
        ),
    ]
