# Generated by Django 2.2.13 on 2021-06-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_auto_20200301_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allmedalist',
            options={'ordering': ['-year'], 'verbose_name': 'Медалісти', 'verbose_name_plural': 'Медалісти'},
        ),
    ]
