# Generated by Django 2.2.2 on 2020-03-01 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='class_name',
            field=models.CharField(max_length=40, verbose_name='Клас'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=ckeditor.fields.RichTextField(verbose_name='Завдання'),
        ),
    ]
