# Generated by Django 2.2.2 on 2020-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_learning', '0002_auto_20200301_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Завдання для дистанційного вивчення', 'verbose_name_plural': 'Завдання для дистанційного вивчення'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(max_length=140, null=True, verbose_name='Посилання'),
        ),
    ]
