# Generated by Django 2.2.2 on 2019-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0008_auto_20190724_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
