# Generated by Django 2.2.2 on 2019-08-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0009_auto_20190728_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
