# Generated by Django 2.2.2 on 2019-08-31 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0010_auto_20190804_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбоми'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photogallery/static/photogallery', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Назва'),
        ),
    ]
