# Generated by Django 2.2.2 on 2019-06-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_category_rank_specialposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='teachers.Category'),
        ),
    ]
