# Generated by Django 2.2.2 on 2019-06-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rank',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='teachers.Rank'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='special_position',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='teachers.SpecialPosition'),
        ),
    ]
