# Generated by Django 2.2.2 on 2019-06-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20190609_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='methodical_association',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='teachers.MethodicalAssociation'),
        ),
    ]
