# Generated by Django 2.2.2 on 2019-06-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20190609_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='methodical_association',
        ),
        migrations.AddField(
            model_name='teacher',
            name='methodical_association',
            field=models.ManyToManyField(to='teachers.MethodicalAssociation'),
        ),
    ]
