# Generated by Django 2.2.2 on 2019-06-09 14:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20190609_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default='0', max_length=3),
        ),
    ]
