# Generated by Django 2.2.2 on 2019-06-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20190609_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.ManyToManyField(to='teachers.Lesson'),
        ),
    ]
