# Generated by Django 2.2.2 on 2019-07-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_auto_20190725_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Category'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Rank'),
        ),
    ]
