# Generated by Django 2.2.2 on 2019-08-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_auto_20190728_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='methodicalassociation',
            options={'verbose_name': "Методичне об'єднання", 'verbose_name_plural': "Методичні об'єднання"},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Звання', 'verbose_name_plural': 'Звання'},
        ),
        migrations.AlterModelOptions(
            name='specialposition',
            options={'verbose_name': 'Особливий статус', 'verbose_name_plural': 'Особливі статуси'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='По батькові'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_year',
            field=models.IntegerField(default=1990, verbose_name='Рік приходу на роботу'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='methodicalassociation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='specialposition',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(max_length=20, verbose_name='Прізвище'),
        ),
    ]
