# Generated by Django 2.2.2 on 2019-08-31 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_auto_20190831_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='join_year',
        ),
    ]
