# Generated by Django 2.2.2 on 2020-03-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_remove_teacher_join_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodicalassociation',
            options={'verbose_name': 'Предметно-методична комісія', 'verbose_name_plural': 'Предметно-методичні комісії'},
        ),
    ]
