# Generated by Django 2.2.13 on 2021-06-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_teacher_fathers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRetraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Рік')),
            ],
            options={
                'verbose_name': 'Курсова перепідготовка ',
                'verbose_name_plural': 'Курсова перепідготовка',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['second_name'], 'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
        migrations.CreateModel(
            name='CourseRetrainingTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='Дата початку курсу')),
                ('end_time', models.DateField(verbose_name='Дата завершення курсу')),
                ('course_code', models.CharField(max_length=20, verbose_name='Код курсу')),
                ('variant', models.CharField(max_length=20, verbose_name='Назва варіанту')),
                ('course_name', models.CharField(max_length=255, verbose_name='Назва курсу')),
                ('certificate_number', models.CharField(max_length=255, verbose_name='Номер сертифіката')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.CourseRetraining')),
            ],
            options={
                'verbose_name': 'Вчитель курсової перепідготовки',
                'verbose_name_plural': 'Вчителі курсової перепідготовки',
            },
        ),
    ]
