# Generated by Django 2.2.10 on 2020-07-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0018_auto_20200301_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=5, verbose_name='Клас')),
            ],
            options={
                'verbose_name': 'Розклад класу',
                'verbose_name_plural': 'Розклади класів',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_consisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassSchedule')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Lesson')),
            ],
        ),
    ]
