# Generated by Django 2.2.10 on 2020-07-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_auto_20200301_1407'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Mo', 'Понеділок'), ('Tu', 'Вівторок'), ('We', 'Середа'), ('Th', 'Четвер'), ('Fr', "П'ятниця")], max_length=2, null=True, verbose_name='День')),
                ('index', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True, verbose_name='Номер уроку')),
                ('class_consisting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassSchedule')),
                ('lesson_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Lesson')),
            ],
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
