# Generated by Django 2.2.10 on 2020-07-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200702_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlesson',
            name='subgroup',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True, verbose_name='Підгрупа'),
        ),
        migrations.AlterField(
            model_name='classlesson',
            name='day',
            field=models.CharField(choices=[('Mo', 'Понеділок'), ('Tu', 'Вівторок'), ('We', 'Середа'), ('Th', 'Четвер'), ('Fr', "П'ятниця")], default='Mo', max_length=2, verbose_name='День'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlesson',
            name='index',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=1, verbose_name='Номер уроку'),
            preserve_default=False,
        ),
    ]
