# Generated by Django 2.2.10 on 2020-07-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200705_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlesson',
            name='spec_week',
            field=models.CharField(blank=True, choices=[('Nu', 'Чисельник'), ('De', 'Знаменник')], max_length=2, null=True, verbose_name='Підгрупа'),
        ),
    ]
