# Generated by Django 2.2.10 on 2020-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_classlesson_spec_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlesson',
            name='spec_week',
            field=models.CharField(blank=True, choices=[('Nu', 'Чисельник'), ('De', 'Знаменник')], max_length=2, null=True, verbose_name='Тиждень'),
        ),
    ]
